apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  namespace: default
  labels:
    app: ml-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ml-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ml-deployment
    spec:
      containers:
        - name: ml-deployment
          image: aksregistryat.azurecr.io/machine-learning-deployment-using-docker:15ea65df9442ac4ea505d28144bb6805f10f1949
          imagePullPolicy: IfNotPresent
          resources: {}
